### ISSUE TITLE
Dont throw a warning for missing orientation if there is no parking

### ISSUE THREAD

**Issue by SupaplexOSM** [osmberlin/osm-tag-updater#10]
If there is no parking on both sides, then there is no need for a orientation tag. Therefore, the warning "The primary orientation key `parking:$side:orientation=*` is missing." should not appear in this case.

**Comment by SupaplexOSM** [comment]
This issue also applies to `separate`.

**Comment by tordans** [comment]
Nice catch! Fixed in 0.0.13, live in a minute.

This is also a great example of the complexity that is cause by the `:both` case. I expanded the orientation-check to look at the primary key first. This is the test file I had to write to make sure I have all cases… https://github.com/osmberlin/osm-tag-updater/commit/d2188f7f4d26a3d59809bfa5eccb5bb413b94c37#diff-bde921838f036e837226885d227563494455070f3d4cbe1772ee80ed5d632df5
